### PR TITLE
fix: update russian country name for Belarus (BY) 

### PR DESCRIPTION
**Pull request by cgehuzi**
Change name from Белоруссия to Беларусь.

### CODE REVIEW

**Comment by stefangabos** [comment]
According to [this](https://ru.wikipedia.org/wiki/%D0%91%D0%B5%D0%BB%D0%BE%D1%80%D1%83%D1%81%D1%81%D0%B8%D1%8F) both are fine. Also, the page uses as main name the one that we already have

**Comment by cgehuzi** [comment]
Yes. But this name was deprecated in Belarus from 1991 year.

**Comment by stefangabos** [comment]
I pushed a commit where this is fixed. Do you need me to publish a release?

**Comment by cgehuzi** [comment]
Yes, publish please. Thanks! 🔥

**Comment by stefangabos** [comment]
done

**Pull request closed without merging**
