### PR TITLE
fix simplified Chinese and traditional Chinese mix

### PR DESCRIPTION
**Pull request by sun-jiao**

### CODE REVIEW

**Comment by sun-jiao** [comment]
I saw your comment in another pull request, you have a script, and I don't know if your script get data from wiki code or the webpage. 

The Chinese Wikipedia can auto convert between traditional and simplified Chinese, so the country names in wiki code may be mixed.(and it's not allowed to change between them.) If your script get data from webpage, that will be great, you should just change the target URL to a concerted page. If you get data from wiki code, a manual convert will be needed.

**Comment by stefangabos** [comment]
[This](https://zh.wikipedia.org/wiki/ISO_3166-1) is the link from where I am taking country names. Obviously, I take the country names by parsing the HTML code in the page, but whatever you see is the same as what there is in the page's code.

**Comment by stefangabos** [comment]
Can you please give me a link to that page set up so that it shows what I need to parse?

**Comment by stefangabos** [comment]
Apparently what I see when I am accessing the page is in - according to Google Translate - *Chinese (Traditional)*

**Comment by stefangabos** [comment]
Additionally, switching via Google Translate from traditional to simplified Chinese makes no difference in country names - at least that is how it seems to me

**Comment by sun-jiao** [comment]
> [This](https://zh.wikipedia.org/wiki/ISO_3166-1) is the link from where I am taking country names. Obviously, I take the country names by parsing the HTML code in the page, but whatever you see is the same as what there is in the page's code.

Simplified Chinese: 
https://zh.wikipedia.org/zh-cn/ISO_3166-1

**Comment by stefangabos** [comment]
done. do i have to include other variations of the Chinese language? Like zh-tw, zh-hk, zh-mo, zh-my, etc. ? if so, which ones should I add? thank you for helping!

**Comment by sun-jiao** [comment]
> done. do i have to include other variations of the Chinese language? Like zh-tw, zh-hk, zh-mo, zh-my, etc. ? if so, which ones should I add? thank you for helping!

I think it's a good idea to add zh-tw and zh-hk version, and no need to add other variants.
https://zh.wikipedia.org/zh-tw/ISO_3166-1
https://zh.wikipedia.org/zh-hk/ISO_3166-1

zh-mo is almost same as zh-hk. zh-my and zh-sg are almost same as zh-cn.
Can you please update the cn version again? I just updated the simplified Chinese name of 876,wf,wlf in Wikipedia.

**Comment by sun-jiao** [comment]
> done. do i have to include other variations of the Chinese language? Like zh-tw, zh-hk, zh-mo, zh-my, etc. ? if so, which ones should I add? thank you for helping!

btw, Would you like to add svg version of flags?  You can get filenames of them from the html, and find them in wikimedia commons.

**Comment by stefangabos** [comment]
i have reprocessed the wikipedia page and update the country's name for the one you changed.
i will also include the other variations of the chinese language in the coming days.
good idea about the svg flags, i will also look into that.
thanks a lot for all your support!

**Comment by sun-jiao** [comment]
> i have reprocessed the wikipedia page and updated the country name for the one you changed.
> i will also include the other variations of the chinese language in the coming days.
> good idea about the svg flags, i will also look into that.
> thanks a lot for all your support!

Thank you for this pleasant discussion and for your excellent project.

**Pull request closed without merging**
