### PR TITLE
Add Traditional Chinese translation

### PR DESCRIPTION
**Pull request by hirakujira**
I added Traditional Chinese (zh_TW) translation.

### CODE REVIEW

**Comment by hirakujira** [comment]
It's based on [https://zh.wikipedia.org/wiki/ISO_3166-1](https://zh.wikipedia.org/wiki/ISO_3166-1) but has minor changes because some names are not updated in this list. 

For example: NL (Netherlands) announced "尼德蘭" should be the official Chinese translation since 2020 but wikipedia still shows "荷蘭", which means "Holland".

Also, TW (Taiwan, Province of China) translated to "台灣", because the translation of zh_TW is for people in Taiwan and we don't agree that Taiwan is a province of China.

**Comment by stefangabos** [comment]
Since the lists are compiled automatically from Wikipedia, I can't take pull requests. 
But, what I did was to add https://zh.wikipedia.org/wiki/ISO_3166-1 to my lists of sources to fetch and I added the changes you requested for the Netherlands and for Taiwan.

Please have a look - it's in the `data/zh` folder. I would appreciateit  if you'd change the naming for Netherlands on the Wikipedia page, so I don't have to always overwrite it.

Thank you!

**Comment by stefangabos** [comment]
I added it also to http://stefangabos.github.io/world_countries/

**Comment by hirakujira** [comment]
Hello, 
I'm sorry that I made a mistake, Netherland can be pulled directly from Wikipedia. No need modifications. The only thing that need to changed manually is Taiwan.

And also, the data you fetched seems contains Simplified Chinese because Wikipedia shows Traditional Chinese on my computer automatically, but not on your side

Please fetch this URL instead: [https://zh.wikipedia.org/zh-tw/ISO_3166-1](https://zh.wikipedia.org/zh-tw/ISO_3166-1), I'm sorry for the inconvenience and very appreciated for your patience.

**Comment by stefangabos** [comment]
Don't worry about it - thank **you** for your help!
I updated the lists, please have a look

**Comment by hirakujira** [comment]
Yes, it's perfect now, thanks for your help!

**Comment by stefangabos** [comment]
I published a new release - `1.1.1`, and it is now available via [npm](https://www.npmjs.com/package/world_countries_lists) or from [here](http://stefangabos.github.io/world_countries/)
Thank you!

**Pull request closed without merging**
