### PR TITLE
Update countries.csv

### PR DESCRIPTION
**Pull request by sebastiaanlooijen**
I've changed Micronesia to Micronesië. Source: https://nl.wikipedia.org/wiki/Micronesi%C3%AB

### CODE REVIEW

**Comment by stefangabos** [comment]
Please update the entry on Wikipedia at https://nl.wikipedia.org/wiki/ISO_3166-1 as this is where the data is pulled from. 
Thank you!

**Comment by cornelius-illi** [comment]
Hi Stefan, I guess your script is not working properly or hasn't pulled the most recent version. These countries are listed, but missing in your list of countries: 

ISO 3166-2:MO
ISO 3166-2:TW
ISO 3166-2:HK

**Comment by stefangabos** [comment]
All of those are present in the `world.csv` file. 
Read on the project's page about member states and sovereign states

**Comment by sebastiaanlooijen** [comment]
There seems to be a difference between the name of the country and the name of the group of islands... Micronesia is correct. Issue can be closed. Thanks for the great work!

**Pull request closed without merging**
